import type { Streamer } from "./streamer.model";

export const streamers: Streamer[] = [
  { twitchUsername: "1_upp" },
  { twitchUsername: "1971printer", dkfUsername: "1971printer" },
  { twitchUsername: "80sArcadeKid", dkfUsername: "80sArcadeKid" },
  { twitchUsername: "879500", dkfUsername: "Rick Fothergill" },
  { twitchUsername: "AaronTruitt", dkfUsername: "aarontruitt" },
  { twitchUsername: "aftershoke" },
  { twitchUsername: "alumbrada", dkfUsername: "alumbrada" },
  { twitchUsername: "AndrewG", dkfUsername: "andrewg" },
  { twitchUsername: "anningmay", dkfUsername: "anningmay" },
  { twitchUsername: "ArcadePlayer_ABC", dkfUsername: "ArcadePlayer_ABC" },
  { twitchUsername: "ATL_Arcade", dkfUsername: "2084" },
  { twitchUsername: "Bach730", dkfUsername: "Bach730" },
  { twitchUsername: "BackdoorFred", dkfUsername: "BackdoorFred" },
  { twitchUsername: "barrra", dkfUsername: "Barra" },
  { twitchUsername: "bensweeneyonbass", dkfUsername: "bensweeneyonbass" },
  { twitchUsername: "Billhouse", dkfUsername: "Billhouse" },
  { twitchUsername: "BillyGaines", dkfUsername: "BillyGaines" },
  { twitchUsername: "bonerforce75", dkfUsername: "bonerforce" },
  { twitchUsername: "bookootabor", dkfUsername: "Bookoo Tabor" },
  { twitchUsername: "Bradtech519", dkfUsername: "bradtech519" },
  { twitchUsername: "Bruzzi", dkfUsername: "sevenup1203" },
  { twitchUsername: "CaptainJivePants", dkfUsername: "CaptainJivePants" },
  { twitchUsername: "captnkong", dkfUsername: "captnkong" },
  { twitchUsername: "CarrieSwidecki" },
  { twitchUsername: "Casinokid420" },
  { twitchUsername: "CharlieFar", dkfUsername: "CharlieFar" },
  { twitchUsername: "ChrisP_Kreme", dkfUsername: "ChrisP" },
  { twitchUsername: "classiccoinops", dkfUsername: "mylar" },
  { twitchUsername: "colmanARCADEgamer", dkfUsername: "colman paolo" },
  { twitchUsername: "crazyfox351", dkfUsername: "crazyfox351" },
  { twitchUsername: "creech777", dkfUsername: "creech" },
  { twitchUsername: "d3rtus" },
  { twitchUsername: "D3scride", dkfUsername: "d3scride" },
  { twitchUsername: "DaLar75", dkfUsername: "DaLar" },
  { twitchUsername: "DanielSolisDK", dkfUsername: "DanielDKSolis" },
  { twitchUsername: "danman123546", dkfUsername: "danman123456" },
  { twitchUsername: "Dazzer_", dkfUsername: "Dazzer" },
  { twitchUsername: "dbcooper777", dkfUsername: "D.B. Cooper" }, 
  { twitchUsername: "DearestAbby", dkfUsername: "dearestabby" },
  { twitchUsername: "DennyDevit0", dkfUsername: "DennyDevito" },
  { twitchUsername: "DigitalJazzArcade", dkfUsername: "SamMcNear" },
  { twitchUsername: "djgubernot", dkfUsername: "djgubernot1" },
  { twitchUsername: "dk3champ", dkfUsername: "homerwannabee" },
  { twitchUsername: "dk_1981", dkfUsername: "Matt" },
  { twitchUsername: "DKMikey77", dkfUsername: "VIMikey" },
  { twitchUsername: "dknetter", dkfUsername: "dknetter" },
  { twitchUsername: "dollopuss", dkfUsername: "dollopuss" },
  { twitchUsername: "DonkeyKongJunior83", dkfUsername: "DKJR" },
  { twitchUsername: "doonze11", dkfUsername: "jwade614" },
  { twitchUsername: "Dr_SaGe", dkfUsername: "Dr_SaGe" },
  { twitchUsername: "dtaylorkong", dkfUsername: "Dallas Taylor" },
  { twitchUsername: "Duaber", dkfUsername: "Duaber" },
  { twitchUsername: "Durden77", dkfUsername: "durden77" },
  { twitchUsername: "dwwnp", dkfUsername: "VON" },
  { twitchUsername: "dzn_duke", dkfUsername: "dnickolas" },
  { twitchUsername: "eij9genw", dkfUsername: "leejunfan777" },
  { twitchUsername: "Eric_Abroad", dkfUsername: "emart756" },
  { twitchUsername: "evann04_", dkfUsername: "Evan04" },
  { twitchUsername: "Evunz", dkfUsername: "Evunz" },
  { twitchUsername: "expandedidea", dkfUsername: "tilt" },
  { twitchUsername: "Falcor781", dkfUsername: "falcor781" },
  { twitchUsername: "FatherlyStreams", dkfUsername: "afatherlykong" },
  { twitchUsername: "fippi", dkfUsername: "fippi" },
  { twitchUsername: "FirebirdTPG", dkfUsername: "FirebirdTPG" },
  { twitchUsername: "flobeamer1922", dkfUsername: "Flobeamer1922" },
  { twitchUsername: "FlyHec", dkfUsername: "Fly" },
  { twitchUsername: "f_symbols", dkfUsername: "f_symbols" },
  { twitchUsername: "furiouswolf666", dkfUsername: "furiouswolf666" },
  { twitchUsername: "futura1978" },
  { twitchUsername: "Gettysburg1863", dkfUsername: "Gettysburg1863" },
  { twitchUsername: "gillkong", dkfUsername: "GILLYKONG" },
  { twitchUsername: "hankchien", dkfUsername: "hchien" },
  { twitchUsername: "hansvskong" },
  { twitchUsername: "ILLSeaBass", dkfUsername: "ILLSeaBass" },
  { twitchUsername: "jammyyy", dkfUsername: "jammyyy" },
  { twitchUsername: "JasonV91", dkfUsername: "JasonV91" },
  { twitchUsername: "jdblacks7", dkfUsername: "jdblacks7" },
  { twitchUsername: "JDllama", dkfUsername: "jdllama" },
  { twitchUsername: "Jeffw356" },
  { twitchUsername: "jimhappy71", dkfUsername: "jimhappy" },
  { twitchUsername: "JMAYden81", dkfUsername: "Jmayden81" },
  { twitchUsername: "joecnnd", dkfUsername: "Bliss1083" },
  { twitchUsername: "Jonesy_Kong", dkfUsername: "Jonesy" },
  { twitchUsername: "jumpmanjack", dkfUsername: "JumpmanJack" },
  { twitchUsername: "just_wolfman_sd", dkfUsername: "wolfman24" },
  { twitchUsername: "Kadows", dkfUsername: "Kadows" },
  { twitchUsername: "kaizen088" },
  { twitchUsername: "kalel99999", dkfUsername: "kalel" },
  { twitchUsername: "Kencade", dkfUsername: "Scoundrl" },
  { twitchUsername: "Kewydee_17", dkfUsername: "Kewydee_17" },
  { twitchUsername: "KrehzTim", dkfUsername: "krehztim" },
  { twitchUsername: "kibbey", dkfUsername: "Kibbey93" },
  { twitchUsername: "KIG666", dkfUsername: "KIG666" },
  { twitchUsername: "laurakingneville", dkfUsername: "LauraKingNeville" },
  { twitchUsername: "LifeReboot", dkfUsername: "lifereboot" },
  { twitchUsername: "Lmdave", dkfUsername: "LMDAVE" },
  { twitchUsername: "LordBBH", dkfUsername: "BBH" },
  { twitchUsername: "LSB85", dkfUsername: "elbee85" },
  { twitchUsername: "Lyriell", dkfUsername: "Lyriell" },
  { twitchUsername: "magrinder", dkfUsername: "Max" },
  { twitchUsername: "MajesticOne_Nick", dkfUsername: "Majesticone" },
  { twitchUsername: "MarinoMitch13", dkfUsername: "marinomitch13" },
  { twitchUsername: "Marky_d", dkfUsername: "marky_d" },
  { twitchUsername: "mattbuc16", dkfUsername: "mattbuc16" },
  { twitchUsername: "mattkarvonen", dkfUsername: "MattyK" },
  { twitchUsername: "maximumsteve", dkfUsername: "maximumsteve" },
  { twitchUsername: "mcporkchop54", dkfUsername: "Mcporkchop54" },
  { twitchUsername: "Meerkat_Games", dkfUsername: "MJMeerman" },
  { twitchUsername: "MegaSuperRad", dkfUsername: "KongKlub" },
  { twitchUsername: "melkond" },
  { twitchUsername: "MickyWinz", dkfUsername: "MickyWinz" },
  { twitchUsername: "milehighdt", dkfUsername: "Milehighdt" },
  { twitchUsername: "MrPitchy", dkfUsername: "Itsmrpitchy" },
  { twitchUsername: "mrvaya", dkfUsername: "mrvaya" },
  { twitchUsername: "mschrock26", dkfUsername: "M.Schrock" },
  { twitchUsername: "MultifariousGamer" },
  { twitchUsername: "Muscleandfitness", dkfUsername: "muscleandfitness" },
  { twitchUsername: "nsheeks" },
  { twitchUsername: "NWnike", dkfUsername: "NWnike" },
  { twitchUsername: "okinawa2" },
  { twitchUsername: "oldschoolgpk333" },
  { twitchUsername: "Opticsrs", dkfUsername: "Optics" },
  { twitchUsername: "Owlnonymous" },
  { twitchUsername: "Pearl_", dkfUsername: "Pearl" },
  { twitchUsername: "Pelly222", dkfUsername: "Pelly" },
  { twitchUsername: "Phil_Tony", dkfUsername: "Tony" },
  { twitchUsername: "pikachu942", dkfUsername: "Miketastic5" },
  { twitchUsername: "pipelinetrash", dkfUsername: "angrybeaver21" },
  { twitchUsername: "Prow7", dkfUsername: "Prow" },
  { twitchUsername: "QAOP_Spaceman", dkfUsername: "QAOP Spaceman" },
  { twitchUsername: "Ratix98" },
  { twitchUsername: "rayfinkel", dkfUsername: "rayfinkel" },
  { twitchUsername: "Rdrunner0077", dkfUsername: "rdrunner" },
  { twitchUsername: "rdy_plr1", dkfUsername: "Les.coffman" },
  { twitchUsername: "reinke0314", dkfUsername: "Reinke314" },
  { twitchUsername: "Retrogaming2084", dkfUsername: "JoshtheGamer" },
  { twitchUsername: "Retroper", dkfUsername: "RetroPER" },
  { twitchUsername: "retrotonight", dkfUsername: "retrotonight" },
  { twitchUsername: "RiffRaffGames", dkfUsername: "riffraff" },
  { twitchUsername: "Rolledcigs", dkfUsername: "Rolledcigs" },
  { twitchUsername: "rosebud360", dkfUsername: "Rosebud" },
  { twitchUsername: "rygar412", dkfUsername: "rygar412" },
  { twitchUsername: "sapphire_drag0n", dkfUsername: "sapphire_drag0n" },
  { twitchUsername: "serginioso" },
  { twitchUsername: "serphintizer", dkfUsername: "serphintizer" },
  { twitchUsername: "shatty" },
  { twitchUsername: "shaunanigans88", dkfUsername: "Shaunanigans" },
  { twitchUsername: "Shigerumiyamoto", dkfUsername: "jumpman" },
  { twitchUsername: "Sid_Seattle", dkfUsername: "Sidseattle" },
  { twitchUsername: "sikraiken", dkfUsername: "sikraiken" },
  { twitchUsername: "silkyfresh", dkfUsername: "godfather" },
  { twitchUsername: "SimpleDack", dkfUsername: "Simple_Dack" },
  { twitchUsername: "SithOfSpades", dkfUsername: "SithOfSpades" },
  { twitchUsername: "sleepygarysgamestream", dkfUsername: "sleepygary" },
  { twitchUsername: "smoke4659" },
  { twitchUsername: "Snicklefritzx", dkfUsername: "snicklefritzx" },
  { twitchUsername: "Sock__Master", dkfUsername: "Sock Master" },
  { twitchUsername: "SoltyD", dkfUsername: "SoltyD" },
  { twitchUsername: "spindaddy", dkfUsername: "spindaddy56" },
  { twitchUsername: "stella_blue", dkfUsername: "stella_blue" },
  { twitchUsername: "summeraino", dkfUsername: "joekassel" },
  { twitchUsername: "synappzz", dkfUsername: "Synappzz" },
  { twitchUsername: "synthchemist", dkfUsername: "synthchemist" },
  { twitchUsername: "Syscrusher", dkfUsername: "syscrusher" },
  { twitchUsername: "TAGGSTA", dkfUsername: "Sean_Taggsta_OutRun_86" },
  { twitchUsername: "tarkus1977", dkfUsername: "tarkus1977" },
  { twitchUsername: "TBE_SWE", dkfUsername: "TBE" },
  { twitchUsername: "tjb3531", dkfUsername: "tjb3531" },
  { twitchUsername: "ThadJarvice", dkfUsername: "ThadJarvice" },
  { twitchUsername: "TheABL", dkfUsername: "TheABL" },
  { twitchUsername: "thelivingdaylights", dkfUsername: "PaperTig3rs" },
  { twitchUsername: "the_pro", dkfUsername: "The Pro" },
  { twitchUsername: "TheScubaPup", dkfUsername: "Shamrock" },
  { twitchUsername: "The_Shed_Arcade", dkfUsername: "Muerto" },
  { twitchUsername: "TheSunshineFund", dkfUsername: "TheSunshineFund" },
  { twitchUsername: "timhett", dkfUsername: "timhett" },
  { twitchUsername: "Timmell", dkfUsername: "michaelsroka" },
  { twitchUsername: "tippington", dkfUsername: "tippington" },
  { twitchUsername: "twinxen", dkfUsername: "twinxen" },
  { twitchUsername: "twitchshane", dkfUsername: "mameshane" },
  { twitchUsername: "tudose", dkfUsername: "tudose" },
  { twitchUsername: "ukpdkf", dkfUsername: "UKP" },
  { twitchUsername: "up2ng", dkfUsername: "up2ng" },
  { twitchUsername: "VerneV", dkfUsername: "Vern" },
  { twitchUsername: "VeryApe121", dkfUsername: "VeryApe121" },
  { twitchUsername: "weiwovaseiba", dkfUsername: "weiwovaseiba" },
  { twitchUsername: "WesCopeland", dkfUsername: "wc" },
  { twitchUsername: "WFLImusic", dkfUsername: "wflimusic" },
  { twitchUsername: "wv_pinball", dkfUsername: "wvapinball" },
  { twitchUsername: "wwdkong", dkfUsername: "ww" },
  { twitchUsername: "xelnia", dkfUsername: "xelnia" },
  { twitchUsername: "Xermon54", dkfUsername: "Xermon54" },
  { twitchUsername: "YesAffinity", dkfUsername: "YesAffinity" },
  { twitchUsername: "Zamboni93", dkfUsername: "zamboni93" },
  { twitchUsername: "Zapwai", dkfUsername: "zapwai" },
  { twitchUsername: "ZedIsDead", dkfUsername: "ZedIsDead" },
  { twitchUsername: "Zerst", dkfUsername: "Zerst" },
  { twitchUsername: "Ziiggys", dkfUsername: "Ziggy" },
  { twitchUsername: "Zmick_tricK", dkfUsername: "Zmick_tricK" },
  { twitchUsername: "Zotmeister" },
  { twitchUsername: "2084arcade" },
  { twitchUsername: "battleofthearcades" },
  { twitchUsername: "FullBlastArcade" },
  { twitchUsername: "GallopingGhostArcade" },
  { twitchUsername: "GallopingGhostClassics" },
  { twitchUsername: "GamesDoneQuick" },
  { twitchUsername: "Knife_horse" },
  { twitchUsername: "MeowWolf" },
  { twitchUsername: "netherworldarcade" },
  { twitchUsername: "Pincadia" },
  { twitchUsername: "Retrocade" },
  { twitchUsername: "vortexarcadeAR", dkfUsername: "vortexarcade" },
  { twitchUsername: "Z82RetrocadeSherwood" },
];
