import type { Streamer } from "./streamer.model";

export const streamers: Streamer[] = [
  { twitchUsername: "80sArcadeKid", dkfUsername: "80sArcadeKid" },
  { twitchUsername: "ATL_Arcade", dkfUsername: "2084" },
  { twitchUsername: "bonerforce75", dkfUsername: "bonerforce" },
  { twitchUsername: "Bruzzi", dkfUsername: "sevenup1203" },
  { twitchUsername: "ChrisP_Kreme", dkfUsername: "ChrisP" }
  { twitchUsername: "crazyfox351", dkfUsername: "crazyfox351" },,
  { twitchUsername: "dwwnp", dkfUsername: "VON" },
  { twitchUsername: "evann04_", dkfUsername: "Evan04" },
  { twitchUsername: "furiouswolf666", dkfUsername: "furiouswolf666" },
  { twitchUsername: "futura1978" },
  { twitchUsername: "Jeffw356" },
  { twitchUsername: "jdblacks7", dkfUsername: "jdblacks7" },
  { twitchUsername: "jimhappy71", dkfUsername: "jimhappy" },
  { twitchUsername: "kaizen088" },
  { twitchUsername: "Lmdave", dkfUsername: "LMDAVE" },
  { twitchUsername: "LordBBH", dkfUsername: "BBH" },
  { twitchUsername: "milehighdt", dkfUsername: "Milehighdt" },
  { twitchUsername: "muscleandfitness", dkfUsername: "muscleandfitness" },
  { twitchUsername: "Prow7", dkfUsername: "Prow" },
  { twitchUsername: "rayfinkel", dkfUsername: "rayfinkel" },
  { twitchUsername: "retrotonight", dkfUsername: "retrotonight" },
  { twitchUsername: "rdy_plr1", dkfUsername: "Les.coffman" },
  { twitchUsername: "sapphire_drag0n", dkfUsername: "sapphire_drag0n" },
  { twitchUsername: "SimpleDack", dkfUsername: "Simple_Dack" },
  { twitchUsername: "synappzz", dkfUsername: "Synappzz" },
  { twitchUsername: "Syscrusher", dkfUsername: "syscrusher" },
  { twitchUsername: "twitchshane", dkfUsername: "mameshane" },
  { twitchUsername: "tudose", dkfUsername: "tudose" },
  { twitchUsername: "up2ng", dkfUsername: "up2ng" },
  { twitchUsername: "VerneV", dkfUsername: "Vern" },  
  { twitchUsername: "WesCopeland", dkfUsername: "wc" },
  { twitchUsername: "xelnia", dkfUsername: "xelnia" },
];
